host = 'wx2';	// hostname or IP address
port = 9001;
topic = 'vessels'; //"#" for everything		// topic to subscribe to
useTLS = false;
username = "";
password = "";
path = "";
cleansession = true;
reconnectTimeout = 5000;
client_id = new Date().getTime().toString();
