host = 'm14.cloudmqtt.com';	// hostname or IP address
port = 31303;
topic = 'vessels/#'; //"#" for everything		// topic to subscribe to
useTLS = true;
username = "***";
password = "***";
path = "";
cleansession = true;
reconnectTimeout = 5000;
client_id = new Date().getTime().toString();
